name: Static Site Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v3

      - name: Dosya yapısını kontrol et
        run: |
          echo "Proje dosyaları:"
          ls -la
          echo "✅ Statik site doğrulandı. Build başarılı."
